<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Car;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Internal\Hydration\HydrationException;
use Doctrine\ORM\Internal\Hydration\ObjectHydrator;
use Doctrine\ORM\Query;
use Doctrine\ORM\Query\Expr;

/**
 * CarRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your
 * own custom repository methods below.
 */
class CarRepository extends EntityRepository
{

    public function getAllCarsByMake(string $make)
    {
        return $this->createQueryBuilder('c')
          ->where('c.make = :make')
          ->setParameter('make', $make)
          ->addOrderBy('c.model', 'ASC')
          ->addOrderBy('c.travelledDistance', 'DESC')
          ->getQuery()
          ->getResult();
    }
}
