<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cars;
use Doctrine\ORM\EntityRepository;

/**
 * CarsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your
 * own custom repository methods below.
 */
class CarsRepository extends EntityRepository
{
    public function getAllCarsByMake(string $make)
    {
        $thing = 'string';

        return $this->createQueryBuilder(Cars::class)
          ->select('cars')
          ->from('AppBundle:Cars', 'cars')
          ->where('cars.make = :make')
          ->setParameter('make', $make)
          ->addOrderBy('cars.model', 'ASC')
          ->addOrderBy('cars.travelledDistance', 'DESC')
          ->getQuery()
          ->getResult();
    }
}
