<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Types\FloatType;
use Doctrine\ORM\EntityRepository;

/**
 * SalesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SalesRepository extends EntityRepository
{

    public function getSalesFullInfo(int $id)
    {
        return $this->createQueryBuilder('sales')
          ->where('sales.id = :id')
          ->setParameter('id', $id)
          ->leftJoin('sales.car', 'car')
          ->leftJoin('sales.customer', 'customer')
          ->getQuery()
          ->getOneOrNullResult();
    }

    public function getAllDiscountedSales()
    {
        return $this->createQueryBuilder('sales')
          ->where('sales.discount > 0')
          ->getQuery()
          ->getResult();
    }

    public function getDiscountedSalesByPercent(float $percent)
    {
        return $this->createQueryBuilder('sales')
          ->where('sales.discount = :percent')
          ->setParameter('percent', $percent, FloatType::FLOAT)
          ->getQuery()
          ->getResult();
    }
}
