<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Types\FloatType;
use Doctrine\ORM\EntityRepository;

/**
 * SalesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SalesRepository extends EntityRepository
{

    public function getSalesFullInfo(int $id)
    {
        return $this->createQueryBuilder('s')
          ->where('s.id = :id')
          ->setParameter('id', $id)
          ->leftJoin('s.car', 'sc')
          ->leftJoin('s.customer', 'scu')
          ->addSelect('sc, scu')
          ->getQuery()
          ->getOneOrNullResult();
    }

    public function getAllDiscountedSales()
    {
        return $this->createQueryBuilder('s')
          ->where('s.discount > 0')
          ->getQuery()
          ->getResult();
    }

    public function getDiscountedSalesByPercent(float $percent)
    {
        return $this->createQueryBuilder('s')
          ->where('s.discount = :percent')
          ->setParameter('percent', $percent, FloatType::FLOAT)
          ->getQuery()
          ->getResult();
    }
}
